### ISSUE TITLE
Reduce learning curve for module contributors

### ISSUE THREAD

**Issue by ericbarefoot** [amoodie/sededu#10]
It would be good to provide a functionality to this entire package where module contributors can have a lower startup barrier. The core functionality would be for the person to install some library, which could provide a command for `create module`, which would initialize a blank template with the minimum necessary parts in that directory. 

This directory would have all the necessary folders, and even contain a how-to guide. Then, once they've checked out the structure, they could replace the standard lipsum and placeholder text, with their own data, scripts, and worksheets.

Related commands could be 

`create activity`
`create document`
and 
`create section`  <- This one requires additional flexibility in the GUI to figure out placement etc.

**Comment by amoodie** [comment]
@ericbarefoot 

Please check out the documentation when you get a chance. I did not do exactly why you proposed, but there is a similar functionality between the "example module" and "template module". 

Start at "contributing" and see what you find. See if you think you'd be able to navigate writing one. 

If there are areas you think need more clarification, comment here and I'll address them.

**Comment by amoodie** [comment]
I have addressed the hot fix clarity. I'm going to close this issue, because I think it has __largely__ been addressed, though as people actually try to develop modules, I can improve the documentation where they see weaknesses.

see PR #49
